// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.8.0
// source: detection.proto

package detection

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ObjectsDetectorClient is the client API for ObjectsDetector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ObjectsDetectorClient interface {
	Detect(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (*ResultResponse, error)
}

type objectsDetectorClient struct {
	cc grpc.ClientConnInterface
}

func NewObjectsDetectorClient(cc grpc.ClientConnInterface) ObjectsDetectorClient {
	return &objectsDetectorClient{cc}
}

func (c *objectsDetectorClient) Detect(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/grpc.ObjectsDetector/Detect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObjectsDetectorServer is the server API for ObjectsDetector service.
// All implementations must embed UnimplementedObjectsDetectorServer
// for forward compatibility
type ObjectsDetectorServer interface {
	Detect(context.Context, *ImageRequest) (*ResultResponse, error)
	mustEmbedUnimplementedObjectsDetectorServer()
}

// UnimplementedObjectsDetectorServer must be embedded to have forward compatible implementations.
type UnimplementedObjectsDetectorServer struct {
}

func (UnimplementedObjectsDetectorServer) Detect(context.Context, *ImageRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Detect not implemented")
}
func (UnimplementedObjectsDetectorServer) mustEmbedUnimplementedObjectsDetectorServer() {}

// UnsafeObjectsDetectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObjectsDetectorServer will
// result in compilation errors.
type UnsafeObjectsDetectorServer interface {
	mustEmbedUnimplementedObjectsDetectorServer()
}

func RegisterObjectsDetectorServer(s grpc.ServiceRegistrar, srv ObjectsDetectorServer) {
	s.RegisterService(&ObjectsDetector_ServiceDesc, srv)
}

func _ObjectsDetector_Detect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectsDetectorServer).Detect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ObjectsDetector/Detect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectsDetectorServer).Detect(ctx, req.(*ImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ObjectsDetector_ServiceDesc is the grpc.ServiceDesc for ObjectsDetector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ObjectsDetector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.ObjectsDetector",
	HandlerType: (*ObjectsDetectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Detect",
			Handler:    _ObjectsDetector_Detect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "detection.proto",
}
